apiVersion: v2
name: cluster-config
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.9.1
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: 1.14.2
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 6.2.3
  - name: grafana
    version: 7.3.7
    repository: https://grafana.github.io/helm-charts
  - name: kube-prometheus-stack
    version: 57.0.3
    repository: https://prometheus-community.github.io/helm-charts
