
argo-cd:
  global:
    domain: totoro.petit-nuage.org

  configs:
    params:
      server.insecure: true

  certificate:
    enabled: true

  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      tls: true

grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - grafana.petit-nuage.org
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.petit-nuage.org

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  persistence:
    enable: true

  admin:
    # Secrets must be generate after kubeseal first installation
    existingSecret: grafana-admin-creds


kube-prometheus-stack:
  alertmanager:
    enabled: false
  kubeProxy:
    enabled: false
  grafana:
    enabled: false

  prometheus:
    # TODO: add resources

    prometheusSpec:
      scrapeInterval: "30s"
      scrapeTimeout: "30s"
      evaluationInterval: "30s"

      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: csi-cinder-classic
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi


sealed-secrets:
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
