
argo-cd:
  global:
    domain: argo-cd.petit-nuage.org

  certificate:
    enabled: true

  server:
    ingress:
      hostname: argo-cd.petit-nuage.org
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      tls: true
