image:
  # Uses app version as default
  tag: ""
  repository: wolveix/satisfactory-server

resources:
 limits:
   memory: 12Gi
 requests:
   cpu: 500m
   memory: 6Gi

env:
  - name: AUTOPAUSE
    value: "true"
  - name: AUTOSAVEINTERVAL
    value: "300"
  - name: AUTOSAVENUM
    value: "3"
  - name: AUTOSAVEONDISCONNECT
    value: "true"
  - name: CRASHREPORT
    value: "true"
  - name: DEBUG
    value: "false"
  - name: DISABLESEASONALEVENTS
    value: "false"
  - name: MAXPLAYERS
    value: "2"
  - name: PGID
    value: "1000"
  - name: PUID
    value: "1000"
  - name: SERVERGAMEPORT
    value: "7777"
  - name: SERVERIP
    value: "0.0.0.0"
  - name: SKIPUPDATE
    value: "false"
  - name: STEAMBETA
    value: "false"
  - name: ROOTLESS
    value: "false"


securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  # needs to be set to false that steamcmd can write to /home/steam
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault