apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yao
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps

  source:
    repoURL: https://github.com/theophanevie/yao.git
    path: chart
    targetRevision: master

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
