apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: statisfactory
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps

  source:
    repoURL: https://github.com/theophanevie/statisfactory-server.git
    path: .
    targetRevision: main

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
