apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-plex
  labels:
    app: plex-qbittorrent
spec:
  selector:
    app: plex-qbittorrent
  ports:
    - name: http
      port: 32400
      targetPort: tcp-plex
      protocol: TCP
